package store

import "github.com/pirbod/chaos-engineering-framework/backend/internal/catalog"

func sampleExperiments() []catalog.Experiment {
	return []catalog.Experiment{
		{
			ID:              "pod-kill",
			Name:            "Pod Kill",
			Type:            "kubernetes",
			Target:          "checkout-api",
			Description:     "Terminates one or more pods to verify replica recovery and alert routing.",
			BlastRadius:     "medium",
			DefaultDuration: "60s",
			SafetyNotes: []string{
				"Run during business-approved windows for tier-1 services.",
				"Verify minimum replica count is greater than one before execution.",
			},
			RunbookID:   "kubernetes-service-degradation",
			LastOutcome: "passed",
			Tags:        []string{"kubernetes", "availability", "litmus"},
		},
		{
			ID:              "network-latency",
			Name:            "Network Latency",
			Type:            "network",
			Target:          "payments-api",
			Description:     "Injects latency between service pods to validate timeout budgets and retry behavior.",
			BlastRadius:     "high",
			DefaultDuration: "30s",
			SafetyNotes: []string{
				"Confirm SLO burn alerts are routed to the owning team.",
				"Start with one pod before expanding to a namespace-level experiment.",
			},
			RunbookID:   "failed-chaos-experiment",
			LastOutcome: "failed",
			Tags:        []string{"latency", "payments", "slo"},
		},
		{
			ID:              "disk-fill",
			Name:            "Disk Fill",
			Type:            "storage",
			Target:          "inventory-worker",
			Description:     "Fills ephemeral disk to validate eviction, backpressure and node pressure alerts.",
			BlastRadius:     "medium",
			DefaultDuration: "45s",
			SafetyNotes: []string{
				"Never target persistent database volumes in the demo profile.",
				"Confirm cleanup job is enabled before execution.",
			},
			RunbookID:   "kubernetes-service-degradation",
			LastOutcome: "passed",
			Tags:        []string{"storage", "node-pressure"},
		},
		{
			ID:              "cpu-hog",
			Name:            "CPU Hog",
			Type:            "compute",
			Target:          "checkout-api",
			Description:     "Consumes CPU on selected pods to validate autoscaling and saturation alerts.",
			BlastRadius:     "medium",
			DefaultDuration: "120s",
			SafetyNotes: []string{
				"Verify HPA target metrics are healthy.",
				"Abort if p95 latency breaches the rollback threshold for two consecutive minutes.",
			},
			RunbookID:   "kubernetes-service-degradation",
			LastOutcome: "passed",
			Tags:        []string{"cpu", "autoscaling", "saturation"},
		},
		{
			ID:              "memory-hog",
			Name:            "Memory Hog",
			Type:            "compute",
			Target:          "recommendations",
			Description:     "Consumes memory to validate OOM recovery and customer-facing fallback paths.",
			BlastRadius:     "low",
			DefaultDuration: "90s",
			SafetyNotes: []string{
				"Keep the experiment scoped to canary pods.",
				"Confirm cached fallback content is available.",
			},
			RunbookID:   "kubernetes-service-degradation",
			LastOutcome: "passed",
			Tags:        []string{"memory", "oom", "fallback"},
		},
		{
			ID:              "node-drain",
			Name:            "Node Drain",
			Type:            "kubernetes",
			Target:          "payments-api",
			Description:     "Drains one worker node to validate pod disruption budgets and zone spread.",
			BlastRadius:     "critical",
			DefaultDuration: "180s",
			SafetyNotes: []string{
				"Requires platform approval for tier-1 services.",
				"Confirm at least three schedulable nodes remain before execution.",
			},
			RunbookID:   "failed-chaos-experiment",
			LastOutcome: "partial",
			Tags:        []string{"node", "pdb", "resilience"},
		},
		{
			ID:              "service-latency",
			Name:            "Service Latency",
			Type:            "application",
			Target:          "gitlab-runners",
			Description:     "Adds latency to a critical platform service dependency to validate developer experience signals.",
			BlastRadius:     "high",
			DefaultDuration: "60s",
			SafetyNotes: []string{
				"Run only against the demo runner group by default.",
				"Notify teams with active release windows before expanding scope.",
			},
			RunbookID:   "gitlab-runner-degradation",
			LastOutcome: "failed",
			Tags:        []string{"gitlab", "developer-experience", "latency"},
		},
	}
}

func sampleServices() []catalog.Service {
	return []catalog.Service{
		{
			ID:                    "checkout-api",
			Name:                  "Checkout API",
			Description:           "Customer checkout workflow and cart finalization API.",
			Owner:                 "checkout-platform@example.com",
			Team:                  "Checkout Platform",
			Tier:                  "tier-1",
			Criticality:           "high",
			RecentErrorRate:       0.018,
			OwnershipCompleteness: 95,
			RunbookIDs:            []string{"kubernetes-service-degradation", "failed-chaos-experiment"},
			ObservabilityMaturity: 88,
			LastExperimentOutcome: "passed",
			SecuritySensitivity:   "medium",
			SLO:                   "99.9% successful checkout requests",
			ExperimentIDs:         []string{"pod-kill", "cpu-hog"},
			Repository:            "https://github.com/pirbod/checkout-api",
			DashboardURL:          "https://grafana.example.com/d/checkout",
		},
		{
			ID:                    "payments-api",
			Name:                  "Payments API",
			Description:           "Payment authorization service integrating with external providers.",
			Owner:                 "payments-oncall@example.com",
			Team:                  "Payments",
			Tier:                  "tier-0",
			Criticality:           "critical",
			RecentErrorRate:       0.041,
			OwnershipCompleteness: 82,
			RunbookIDs:            []string{"failed-chaos-experiment", "datadog-alert-noise"},
			ObservabilityMaturity: 73,
			LastExperimentOutcome: "failed",
			SecuritySensitivity:   "critical",
			SLO:                   "99.95% successful authorization requests",
			ExperimentIDs:         []string{"network-latency", "node-drain"},
			Repository:            "https://gitlab.example.com/payments/payments-api",
			DashboardURL:          "https://app.datadoghq.com/dashboard/payments",
		},
		{
			ID:                    "inventory-worker",
			Name:                  "Inventory Worker",
			Description:           "Asynchronous inventory reconciliation and stock update worker.",
			Owner:                 "supply-chain@example.com",
			Team:                  "Supply Chain",
			Tier:                  "tier-2",
			Criticality:           "medium",
			RecentErrorRate:       0.009,
			OwnershipCompleteness: 68,
			RunbookIDs:            []string{"kubernetes-service-degradation"},
			ObservabilityMaturity: 61,
			LastExperimentOutcome: "passed",
			SecuritySensitivity:   "low",
			SLO:                   "99.5% jobs complete within 10 minutes",
			ExperimentIDs:         []string{"disk-fill"},
			Repository:            "https://github.com/pirbod/inventory-worker",
			DashboardURL:          "https://grafana.example.com/d/inventory",
		},
		{
			ID:                    "gitlab-runners",
			Name:                  "GitLab Runners",
			Description:           "Shared CI runner fleet for product team pipelines.",
			Owner:                 "platform-ci@example.com",
			Team:                  "Platform Engineering",
			Tier:                  "platform-critical",
			Criticality:           "high",
			RecentErrorRate:       0.033,
			OwnershipCompleteness: 90,
			RunbookIDs:            []string{"gitlab-runner-degradation"},
			ObservabilityMaturity: 70,
			LastExperimentOutcome: "failed",
			SecuritySensitivity:   "high",
			SLO:                   "95% jobs start within 2 minutes",
			ExperimentIDs:         []string{"service-latency"},
			Repository:            "https://gitlab.example.com/platform/gitlab-runners",
			DashboardURL:          "https://grafana.example.com/d/gitlab-runners",
		},
		{
			ID:                    "vault-platform",
			Name:                  "Vault Platform",
			Description:           "Central secret distribution and lease management platform.",
			Owner:                 "",
			Team:                  "Security Platform",
			Tier:                  "platform-critical",
			Criticality:           "critical",
			RecentErrorRate:       0.012,
			OwnershipCompleteness: 55,
			RunbookIDs:            []string{"vault-secret-access-failure"},
			ObservabilityMaturity: 66,
			LastExperimentOutcome: "never-run",
			SecuritySensitivity:   "critical",
			SLO:                   "99.99% successful secret read requests",
			ExperimentIDs:         []string{},
			Repository:            "https://github.com/pirbod/vault-platform",
			DashboardURL:          "https://grafana.example.com/d/vault",
		},
	}
}

func sampleRunbooks() []catalog.Runbook {
	return []catalog.Runbook{
		{
			ID:        "failed-chaos-experiment",
			Title:     "Failed Chaos Experiment",
			Summary:   "Triage a chaos experiment that exceeded safety thresholds or failed its hypothesis.",
			AppliesTo: []string{"payments-api", "checkout-api"},
			Severity:  "high",
			Steps: []string{
				"Pause or abort the active experiment in Argo CD or Litmus.",
				"Confirm customer-facing SLO burn and check whether rollback thresholds were breached.",
				"Compare pre-experiment and post-experiment RED metrics for the affected service.",
				"Open an incident if blast radius expanded beyond the approved scope.",
			},
			Checks: []string{
				"Experiment pod is terminated or completed.",
				"Error rate and latency have returned to the pre-experiment baseline.",
				"Owning team has acknowledged the finding.",
			},
			Rollback: []string{
				"Revert the experiment manifest commit or suspend the Argo CD application.",
				"Scale the affected deployment to the last known healthy replica count.",
			},
			Links: []catalog.Link{{Label: "Chaos guide", URL: "/docs/chaos-experiment-guide.md"}},
		},
		{
			ID:        "vault-secret-access-failure",
			Title:     "Vault Secret Access Failure",
			Summary:   "Restore secret access for services using Vault or External Secrets.",
			AppliesTo: []string{"vault-platform"},
			Severity:  "critical",
			Steps: []string{
				"Check Vault health, seal status and active leader.",
				"Validate Kubernetes auth role bindings and token reviewer permissions.",
				"Inspect External Secrets reconciliation errors for the namespace.",
				"Rotate only the affected token or role after confirming least-privilege scope.",
			},
			Checks: []string{
				"Vault reports initialized, unsealed and active.",
				"Application pods can refresh the expected secret version.",
				"No broad root or admin token was used for remediation.",
			},
			Rollback: []string{
				"Disable the latest policy change if it widened blast radius.",
				"Restore the previous ExternalSecret manifest from Git history.",
			},
			Links: []catalog.Link{{Label: "Vault integration", URL: "/docs/vault-integration.md"}},
		},
		{
			ID:        "gitlab-runner-degradation",
			Title:     "GitLab Runner Degradation",
			Summary:   "Triage queueing, executor or network issues affecting CI runner capacity.",
			AppliesTo: []string{"gitlab-runners"},
			Severity:  "medium",
			Steps: []string{
				"Check runner fleet saturation, queued jobs and failing executor logs.",
				"Compare queue time against the platform SLO.",
				"Temporarily route critical projects to a healthy runner group.",
				"Scale runner workers if the degradation is capacity-driven.",
			},
			Checks: []string{
				"New jobs start within the SLO window.",
				"No project token or registration token was exposed during remediation.",
				"Failed jobs were retried only after the root signal improved.",
			},
			Rollback: []string{
				"Restore previous runner autoscaling settings.",
				"Remove temporary project-level runner overrides.",
			},
			Links: []catalog.Link{{Label: "GitLab integration", URL: "/docs/gitlab-integration.md"}},
		},
		{
			ID:        "datadog-alert-noise",
			Title:     "Datadog Alert Noise",
			Summary:   "Reduce noisy monitors while preserving chaos and incident signal quality.",
			AppliesTo: []string{"payments-api"},
			Severity:  "medium",
			Steps: []string{
				"Identify monitors that fired without action during the latest experiment.",
				"Group alerts by service, experiment and risk score tags.",
				"Adjust thresholds only when backed by SLO evidence.",
				"Create an experiment-specific monitor mute window for approved test periods.",
			},
			Checks: []string{
				"Critical risk monitors still page the owning team.",
				"Datadog events include experiment_id and risk_level tags.",
				"Noise reduction changes are captured in Git.",
			},
			Rollback: []string{
				"Revert monitor threshold changes.",
				"Remove temporary mute windows after the experiment.",
			},
			Links: []catalog.Link{{Label: "Datadog integration", URL: "/docs/datadog-integration.md"}},
		},
		{
			ID:        "kubernetes-service-degradation",
			Title:     "Kubernetes Service Degradation",
			Summary:   "Recover a Kubernetes service affected by resource pressure or scheduling disruption.",
			AppliesTo: []string{"checkout-api", "inventory-worker", "recommendations"},
			Severity:  "high",
			Steps: []string{
				"Inspect deployment rollout status, pod restarts and recent events.",
				"Check CPU, memory, disk pressure and network error signals.",
				"Scale replicas or pause the experiment when rollback thresholds are breached.",
				"Capture the failure mode and update the service maturity score.",
			},
			Checks: []string{
				"All expected replicas are ready.",
				"p95 latency and 5xx rate returned to baseline.",
				"Runbook, owner and dashboard links are present in Backstage.",
			},
			Rollback: []string{
				"Revert the experiment manifest.",
				"Restore previous resource requests, limits or HPA settings.",
			},
			Links: []catalog.Link{{Label: "Observability", URL: "/docs/observability.md"}},
		},
	}
}
