apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-chaos-hub.fullname" . }}-backend
  labels:
    {{- include "platform-chaos-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "platform-chaos-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-chaos-hub.fullname" . }}-frontend
  labels:
    {{- include "platform-chaos-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "platform-chaos-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
